//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XUnity.AutoTranslator.Plugin.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XUnity.AutoTranslator.Plugin.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【アイシャドウ】カラー=[Eye Shadow] Color
        ///【アクセサリ(スロット０１)】カラー=[Accessory 01] Color
        ///【アクセサリ(スロット０１)】ツヤの色=[Accessory 01] Shine Color
        ///【アクセサリ(スロット０２)】カラー=[Accessory 02] Color
        ///【アクセサリ(スロット０２)】ツヤの色=[Accessory 02] Shine Color
        ///【アクセサリ(スロット０３)】カラー=[Accessory 03] Color
        ///【アクセサリ(スロット０３)】ツヤの色=[Accessory 03] Shine Color
        ///【アクセサリ(スロット０４)】カラー=[Accessory 04] Color
        ///【アクセサリ(スロット０４)】ツヤの色=[Accessory 04] Shine Color
        ///【アクセサリ(スロット０５)】カラー=[Accessory 05] Color
        ///【アクセサリ(スロット０５)】ツヤの色=[Accessory 05] Shine Color
        ///【アクセサリ(スロット０６)】カラー=[Accessory 06] C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StaticTranslations {
            get {
                return ResourceManager.GetString("StaticTranslations", resourceCulture);
            }
        }
    }
}
