//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XUnity.AutoTranslator.Setup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XUnity.AutoTranslator.Setup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _0Harmony {
            get {
                object obj = ResourceManager.GetObject("_0Harmony", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ExIni {
            get {
                object obj = ResourceManager.GetObject("ExIni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Inject {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Inject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Mdb {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Mdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Pdb {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mono_Cecil_Rocks {
            get {
                object obj = ResourceManager.GetObject("Mono_Cecil_Rocks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReiPatcher {
            get {
                object obj = ResourceManager.GetObject("ReiPatcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Patcher {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Patcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_BaiduTranslate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_BaiduTranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_BingTranslate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_BingTranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_BingTranslateLegitimate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_BingTranslateLegitimate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_Core {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_CustomTranslate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_CustomTranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_GoogleTranslate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_GoogleTranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_GoogleTranslateLegitimate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_GoogleTranslateLegitimate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_Lec {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_Lec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_LecPowerTranslator15 {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_LecPowerTranslator15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_WatsonTranslate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_WatsonTranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XUnity_AutoTranslator_Plugin_YandexTranslate {
            get {
                object obj = ResourceManager.GetObject("XUnity_AutoTranslator_Plugin_YandexTranslate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
